package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseWebdataHomepage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebdataHomepage extends BaseWebdataHomepage<WebdataHomepage> {
	
}
