package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseWebdataHeader;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebdataHeader extends BaseWebdataHeader<WebdataHeader> {
	
}
