package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWebdataHomepage<M extends BaseWebdataHomepage<M>> extends Model<M> implements IBean {

	/**
	 * homepage_data主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * homepage_data主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 定位用名字
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 定位用名字
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 标题文本1
	 */
	public M setTitleStr1(java.lang.String titleStr1) {
		set("titleStr1", titleStr1);
		return (M)this;
	}
	
	/**
	 * 标题文本1
	 */
	public java.lang.String getTitleStr1() {
		return getStr("titleStr1");
	}

	/**
	 * 正文文本1
	 */
	public M setBodyStr1(java.lang.String bodyStr1) {
		set("bodyStr1", bodyStr1);
		return (M)this;
	}
	
	/**
	 * 正文文本1
	 */
	public java.lang.String getBodyStr1() {
		return getStr("bodyStr1");
	}

	/**
	 * 按钮链接
	 */
	public M setButtenUrl(java.lang.String buttenUrl) {
		set("buttenUrl", buttenUrl);
		return (M)this;
	}
	
	/**
	 * 按钮链接
	 */
	public java.lang.String getButtenUrl() {
		return getStr("buttenUrl");
	}

	/**
	 * 图片链接
	 */
	public M setPicUrl(java.lang.String picUrl) {
		set("picUrl", picUrl);
		return (M)this;
	}
	
	/**
	 * 图片链接
	 */
	public java.lang.String getPicUrl() {
		return getStr("picUrl");
	}

	/**
	 * 标题文本2
	 */
	public M setTitleStr2(java.lang.String titleStr2) {
		set("titleStr2", titleStr2);
		return (M)this;
	}
	
	/**
	 * 标题文本2
	 */
	public java.lang.String getTitleStr2() {
		return getStr("titleStr2");
	}

	/**
	 * 标题文本3
	 */
	public M setTitleStr3(java.lang.String titleStr3) {
		set("titleStr3", titleStr3);
		return (M)this;
	}
	
	/**
	 * 标题文本3
	 */
	public java.lang.String getTitleStr3() {
		return getStr("titleStr3");
	}

	/**
	 * 正文文本2
	 */
	public M setBodyStr2(java.lang.String bodyStr2) {
		set("bodyStr2", bodyStr2);
		return (M)this;
	}
	
	/**
	 * 正文文本2
	 */
	public java.lang.String getBodyStr2() {
		return getStr("bodyStr2");
	}

	/**
	 * 正文文本3
	 */
	public M setBodyStr3(java.lang.String bodyStr3) {
		set("bodyStr3", bodyStr3);
		return (M)this;
	}
	
	/**
	 * 正文文本3
	 */
	public java.lang.String getBodyStr3() {
		return getStr("bodyStr3");
	}

}
